### ISSUE TITLE
The "iRacing Formula iR-04 Challenge" fixed/open series (D class) is missing for 2022 S4W1

### ISSUE THREAD

**Issue by Sheppio** [bfiete/iStats#19]
The "iRacing Formula iR-04 Challenge" fixed/open series (D class) is missing for 2022 S4W1.  It is there for 2022_S3W12.  It's definietly running as I just raced in it :)

![image](https://user-images.githubusercontent.com/11756322/189910247-5cdf7973-4e64-4957-9e58-e84e2df2a42a.png)

**Comment by mikebzh44** [comment]
Waiting for @bfiete commit ;)

**Comment by mikebzh44** [comment]
@bfiete  : you can now close this issue ;)
