### ISSUE TITLE
US Open Wheel B missing from Road and US Open Wheel C - Fixed missing from Oval

### ISSUE THREAD

**Issue by TacticalFajita** [bfiete/iStats#34]
Was curious how the IndyCar news has affected the use of the IR18, but noticing that the US Open Wheel B and US Open Wheel C Fixed don't seem too on here.

**Comment by fommil** [comment]
it's in the `Series.txt`, but maybe the name on the server side doesn't match anymore hence it is ignored, c.f. or could be a formatting issue. But the Fixed series is not present at all in the `Series.txt`

```
4157W1 US Open Wheel B - Dallara IR-18
0 US Open Wheel B - Indycar Series : Road
	LICENSE B
	ID 133
...
0 IndyCar iRacing Series : US Open Wheel B - Indycar Series
```
